"""create relationship

Revision ID: 69be4658c45b
Revises: 3972be006dc6
Create Date: 2023-03-14 11:22:03.160496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69be4658c45b'
down_revision = '3972be006dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('articles_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articles_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('articles_id', 'tags_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
